Repository ZenBit-Tech/ctrlchamps_be, pull requests merged in 2023-12, with the labels that each got.

#14 feat: create appoinment
  .eslintrc.js
  src/app.module.ts
  src/common/entities/activity.entity.ts
  src/common/entities/appointment.entity.ts
  src/common/entities/capability.entity.ts
  src/common/entities/caregiver.profile.entity.ts
  src/common/entities/diagnosis.entity.ts
  src/common/entities/seeker-activity.entity.ts
  src/common/entities/seeker-capability.entity.ts
  src/common/entities/seeker-diagnosis.entity.ts
  src/common/entities/seeker-task.entity.ts
  src/common/entities/user.entity.ts
  src/common/enums/api-path.enum.ts
  src/common/enums/error-message.enum.ts
  src/modules/activity/activity.controller.ts
  src/modules/activity/activity.module.ts
  src/modules/activity/activity.service.ts
  src/modules/activity/enums/activity.api-path.enum.ts
  src/modules/appointment/appointment.controller.ts
  src/modules/appointment/appointment.module.ts
  src/modules/appointment/appointment.service.ts
  src/modules/appointment/constants.ts
  src/modules/appointment/dto/create-appointment.dto.ts
  src/modules/appointment/enums/activity-answer.enum.ts
  src/modules/appointment/enums/appointment-create.validation-rule.enum.ts
  src/modules/appointment/enums/appointment-status.enum.ts
  src/modules/appointment/enums/appointment-type.enum.ts
  src/modules/appointment/enums/appointment.api-path.enum.ts
  src/modules/appointment/enums/weekday.enum.ts
  src/modules/appointment/types/appointment.type.ts
  src/modules/auth/auth.module.ts
  src/modules/capability/capability.controller.ts
  src/modules/capability/capability.module.ts
  src/modules/capability/capability.service.ts
  src/modules/capability/enums/capability.api-path.enum.ts
  src/modules/caregiver-info/caregiver-info.module.ts
  src/modules/caregiver-info/caregiver-info.service.ts
  src/modules/diagnosis/diagnosis.controller.ts
  src/modules/diagnosis/diagnosis.module.ts
  src/modules/diagnosis/diagnosis.service.ts
  src/modules/diagnosis/enums/diagnosis.api-path.enum.ts
  src/modules/seed/seed-data/activity.seed.ts
  src/modules/seed/seed-data/capability.seed.ts
  src/modules/seed/seed-data/diagnosis.seed.ts
  src/modules/seed/seed.service.ts
  src/modules/seeker-activity/dto/seeker-activity.dto.ts
  src/modules/seeker-activity/enums/activity-answer.enum.ts
  src/modules/seeker-activity/seeker-activity.module.ts
  src/modules/seeker-activity/seeker-activity.service.ts
  src/modules/seeker-capability/seeker-capability.module.ts
  src/modules/seeker-capability/seeker-capability.service.ts
  src/modules/seeker-diagnosis/seeker-diagnosis.module.ts
  src/modules/seeker-diagnosis/seeker-diagnosis.service.ts
  src/modules/seeker-task/seeker-task.module.ts
  src/modules/seeker-task/seeker-task.service.ts
  src/modules/users/user.service.ts
Labels: good first issue

#15 feat: send appointment email to seeker
  .env.example
  src/common/enums/error-message.enum.ts
  src/modules/appointment/appointment.module.ts
  src/modules/appointment/appointment.service.ts
Labels: good first issue

#18 feat: caregiver appointment email notification
  .env.example
  package-lock.json
  src/common/enums/error-message.enum.ts
  src/modules/appointment/appointment.service.ts
  src/modules/caregiver-info/caregiver-info.service.ts
Labels: good first issue

#20 feat: create appointment api
  package.json
  src/common/enums/error-message.enum.ts
  src/modules/appointment/appointment.constants.ts
  src/modules/appointment/appointment.controller.spec.ts
  src/modules/appointment/appointment.controller.ts
  src/modules/appointment/appointment.service.ts
  src/modules/appointment/constants.ts
  src/modules/appointment/dto/update-appointment.dto.ts
  src/modules/appointment/enums/appointment.api-path.enum.ts
Labels: good first issue

#25 Feat: create agreement emails
  .env.example
  src/modules/virtual-assessment/virtual-assessment.service.ts
Labels: good first issue

#27 fix: add appointment signed status
  src/modules/appointment/appointment.service.ts
  src/modules/appointment/enums/appointment-status.enum.ts
Labels: bug

#28 feat: create virtual assessment accepted email and reminder email
  .env.example
  src/modules/virtual-assessment/virtual-assessment.service.ts
Labels: good first issue

#30 feat: account details requests
  src/common/entities/user.entity.ts
  src/common/enums/api-path.enum.ts
  src/common/enums/error-message.enum.ts
  src/modules/caregiver-info/caregiver-info.controller.ts
  src/modules/users/constants/user-info.constants.ts
  src/modules/users/dto/user-update-info.dto.ts
  src/modules/users/enums/user.api-path.enum.ts
  src/modules/users/user.controller.ts
  src/modules/users/user.module.ts
  src/modules/users/user.service.ts
Labels: enhancement

#31 feat: create activity log and cron for appointment statuses
  package-lock.json
  package.json
  src/app.module.ts
  src/common/entities/activity-log.entity.ts
  src/common/entities/appointment.entity.ts
  src/common/enums/api-path.enum.ts
  src/common/enums/error-message.enum.ts
  src/common/helpers/convert-weekday-to-number.helper.ts
  src/modules/activity-log/activity-log.constants.ts
  src/modules/activity-log/activity-log.controller.spec.ts
  src/modules/activity-log/activity-log.controller.ts
  src/modules/activity-log/activity-log.module.ts
  src/modules/activity-log/activity-log.service.ts
  src/modules/activity-log/dto/create-activity-log.dto.ts
  src/modules/activity-log/enums/activity-log-status.enum.ts
  src/modules/activity-log/enums/activity-log.api-path.enum.ts
  src/modules/appointment/appointment.service.ts
  src/modules/cron/cron.constants.ts
  src/modules/cron/cron.module.ts
  src/modules/cron/cron.service.ts
Labels: good first issue

#32 feat: create reschedule virtual assessment endpoints
  .env.example
  src/common/entities/virtual-assessment.entity.ts
  src/common/enums/error-message.enum.ts
  src/decorators/access-granted.decorator.ts
  src/modules/auth/middleware/auth.middleware.ts
  src/modules/virtual-assessment/constants/virtual-assessment.constant.ts
  src/modules/virtual-assessment/dto/reschedule-assessment.dto.ts
  src/modules/virtual-assessment/enums/virtual-assessment-path.enum.ts
  src/modules/virtual-assessment/virtual-assessment.controller.ts
  src/modules/virtual-assessment/virtual-assessment.service.ts
Labels: good first issue

#38 fix: remove spread in activity log status dto
  src/modules/activity-log/activity-log.service.ts
Labels: bug

#39 fix: transitions
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/caregiver-info/caregiver-info.service.ts
  src/modules/profile/profile.controller.ts
  src/modules/profile/profile.module.ts
  src/modules/profile/profile.service.ts
Labels: bug

#36 fix: appointment creation
  src/common/enums/error-message.enum.ts
  src/modules/appointment/appointment.controller.ts
  src/modules/payment/payment.service.ts
Labels: bug

#35 feat: create password service and endpoint for updating user password
  .env.example
  src/common/enums/error-message.enum.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/caregiver-info/caregiver-info.module.ts
  src/modules/update-password/constants.ts
  src/modules/update-password/update-password.module.ts
  src/modules/update-password/update-password.service.ts
  src/modules/users/dto/update-password.dto.ts
  src/modules/users/enums/user.api-path.enum.ts
  src/modules/users/user.controller.ts
  src/modules/users/user.module.ts
  src/modules/users/user.service.ts
Labels: good first issue
