Repository ZenBit-Tech/ctrlchamps_be, pull requests merged in 2024-01, with the labels that each got.

#41 fix: update caregiver info endpoint
  src/common/entities/caregiver.profile.entity.ts
  src/modules/caregiver-info/caregiver-info.service.ts
  src/modules/caregiver-info/types/detailed-caregiver-info.type.ts
Labels: bug

#42 Features/transaction history
  src/app.module.ts
  src/common/entities/appointment.entity.ts
  src/common/entities/transaction-history.entity.ts
  src/common/entities/user.entity.ts
  src/common/enums/error-message.enum.ts
  src/modules/appointment/appointment.service.ts
  src/modules/caregiver-info/caregiver-info.controller.ts
  src/modules/payment/constants/transaction-history.constants.ts
  src/modules/payment/dto/create-transaction.dto.ts
  src/modules/payment/enums/transaction-api-path.enum.ts
  src/modules/payment/enums/transaction-type.enum.ts
  src/modules/payment/payment.controller.ts
  src/modules/payment/payment.module.ts
  src/modules/payment/payment.service.ts
  src/modules/payment/types/transaction-history.type.ts
Labels: enhancement

#46 feat: create endpoints for fetching admins and deleting users
  .env.example
  src/app.module.ts
  src/common/enums/api-path.enum.ts
  src/common/enums/error-message.enum.ts
  src/modules/admin-panel/admin-panel.controller.spec.ts
  src/modules/admin-panel/admin-panel.controller.ts
  src/modules/admin-panel/admin-panel.module.ts
  src/modules/admin-panel/admin-panel.service.ts
  src/modules/admin-panel/constants/admin-panel.constants.ts
  src/modules/admin-panel/enums/admin.api-path.enum.ts
  src/modules/admin-panel/types/admin-panel.types.ts
  src/modules/users/user.controller.ts
  src/modules/users/user.service.ts
Labels: good first issue

#48 feat: create endpoints for fetching appointments list and deleting an appointment
  src/common/entities/appointment.entity.ts
  src/common/entities/seeker-activity.entity.ts
  src/common/entities/seeker-capability.entity.ts
  src/common/entities/seeker-diagnosis.entity.ts
  src/common/entities/seeker-task.entity.ts
  src/common/entities/transaction-history.entity.ts
  src/common/enums/error-message.enum.ts
  src/modules/admin-panel/admin-panel.controller.ts
  src/modules/admin-panel/admin-panel.module.ts
  src/modules/admin-panel/constants/admin-panel.constants.ts
  src/modules/admin-panel/enums/admin.api-path.enum.ts
  src/modules/appointment/appointment.constants.ts
  src/modules/appointment/appointment.controller.ts
  src/modules/appointment/appointment.service.ts
  src/modules/appointment/enums/sort-query.enum.ts
  src/modules/appointment/types/appointment.type.ts
  src/modules/cron/cron.service.ts
Labels: good first issue

#49 Feat/notifications
  src/app.module.ts
  src/common/entities/appointment.entity.ts
  src/common/entities/notification.entity.ts
  src/common/entities/user.entity.ts
  src/common/enums/api-path.enum.ts
  src/common/enums/error-message.enum.ts
  src/common/enums/notification-message.enum.ts
  src/modules/activity-log/activity-log.module.ts
  src/modules/activity-log/activity-log.service.ts
  src/modules/appointment/appointment.controller.ts
  src/modules/appointment/appointment.module.ts
  src/modules/appointment/appointment.service.ts
  src/modules/cron/cron.module.ts
  src/modules/cron/cron.service.ts
  src/modules/notification/constants/notification.constants.ts
  src/modules/notification/enums/notification.api-path.enum.ts
  src/modules/notification/notification.controller.ts
  src/modules/notification/notification.module.ts
  src/modules/notification/notification.service.ts
  src/modules/payment/payment.service.ts
  src/modules/virtual-assessment/virtual-assessment.module.ts
  src/modules/virtual-assessment/virtual-assessment.service.ts
Labels: enhancement

#51 feat: manage user list
  src/common/entities/user.entity.ts
  src/common/enums/error-message.enum.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/jwt.strategy.ts
  src/modules/users/constants/user-info.constants.ts
  src/modules/users/enums/sort-query.enum.ts
  src/modules/users/enums/user-status.enum.ts
  src/modules/users/enums/user.api-path.enum.ts
  src/modules/users/types/filtered-user-list.type.ts
  src/modules/users/types/user-query.type.ts
  src/modules/users/user.controller.ts
  src/modules/users/user.service.ts
Labels: good first issue

#57 fix: added creating record about payment return
  src/modules/appointment/appointment.service.ts
Labels: bug

#59 fix: added requested you for appointment notification
  src/modules/appointment/appointment.service.ts
Labels: bug

#58 feat: add notifications
  .env.example
  src/common/enums/notification-message.enum.ts
  src/modules/appointment/appointment.service.ts
  src/modules/cron/cron.module.ts
  src/modules/cron/cron.service.ts
  src/modules/virtual-assessment/constants/virtual-assessment.constant.ts
  src/modules/virtual-assessment/virtual-assessment.service.ts
Labels: enhancement

#61 feat: insufficient cost for one hour
  .env.example
  src/common/constants/date.constants.ts
  src/common/entities/appointment.entity.ts
  src/common/enums/notification-message.enum.ts
  src/modules/appointment/appointment.service.ts
  src/modules/appointment/types/appointment.type.ts
  src/modules/cron/cron.constants.ts
  src/modules/cron/cron.service.ts
  src/modules/payment/payment.module.ts
  src/modules/payment/payment.service.ts
  src/modules/payment/types/payment-response.type.ts
Labels: good first issue

#65 feat: add pagination for notifications and transactions
  src/modules/notification/constants/notification.constants.ts
  src/modules/notification/notification.controller.ts
  src/modules/notification/notification.service.ts
  src/modules/notification/types/notification.type.ts
  src/modules/payment/constants/payment.constants.ts
  src/modules/payment/constants/transaction-history.constants.ts
  src/modules/payment/payment.controller.ts
  src/modules/payment/payment.service.ts
  src/modules/payment/types/transaction-query.type.ts
Labels: good first issue

#64 feat: Notifications displaying
  src/common/entities/notification.entity.ts
  src/common/enums/error-message.enum.ts
  src/modules/notification/constants/notification.constants.ts
  src/modules/notification/enums/notification.api-path.enum.ts
  src/modules/notification/notification.controller.ts
  src/modules/notification/notification.service.ts
  src/modules/notification/types/notification.type.ts
Labels: enhancement

#63 feat: update fetching appointments by date
  package.json
  src/modules/appointment/appointment.service.ts
  src/modules/appointment/enums/appointment-status.enum.ts
Labels: enhancement

#69 feat: add return of appointment activity log status
  src/modules/appointment/appointment.service.ts
Labels: enhancement

#70 fix: fix rescheduling delay redirect
  src/modules/virtual-assessment/virtual-assessment.controller.ts
  src/modules/virtual-assessment/virtual-assessment.service.ts
Labels: bug

#71 feat: insufficient costs for appointment
  .env.example
  src/common/constants/constants.ts
  src/common/entities/appointment.entity.ts
  src/common/enums/notification-message.enum.ts
  src/common/helpers/is-more-appointments-days.ts
  src/modules/appointment/appointment.service.ts
  src/modules/appointment/enums/appointment-status.enum.ts
  src/modules/appointment/enums/debt-status.enum.ts
  src/modules/cron/cron.constants.ts
  src/modules/cron/cron.service.ts
  src/modules/notification/notification.service.ts
  src/modules/payment/constants/payment.constants.ts
  src/modules/payment/payment.module.ts
  src/modules/payment/payment.service.ts
Labels: enhancement

#73 fix: update appointment status to Rejected
  src/modules/cron/cron.service.ts
  src/modules/virtual-assessment/virtual-assessment.service.ts
Labels: bug

#76 fix: virtual assessment cron
  src/common/enums/error-message.enum.ts
  src/modules/cron/cron.service.ts
  src/modules/virtual-assessment/virtual-assessment.service.ts
Labels: bug

#79 feat: get reviews
  src/common/enums/error-message.enum.ts
  src/modules/seeker-review/seeker-review.api-path.enum.ts
  src/modules/seeker-review/seeker-review.constants.ts
  src/modules/seeker-review/seeker-review.controller.ts
  src/modules/seeker-review/seeker-review.module.ts
  src/modules/seeker-review/seeker-review.service.ts
  src/modules/seeker-review/types/review-query.type.ts
  src/modules/seeker-review/types/reviews-by-user-id.type.ts
  src/modules/users/user.service.ts
Labels: enhancement

#80 feat: add tasks sorting
  src/common/entities/default-seeker-task.entity.ts
  src/modules/seeker-task/default-seeker-task/default-seeker-task.service.ts
Labels: enhancement

#78 fix: transactions for one hour
  src/modules/appointment/appointment.service.ts
Labels: bug

#81 fix: fix va reschedule logic
  src/modules/virtual-assessment/virtual-assessment.service.ts
Labels: bug

#82 feat: recurring appointments in the calendar
  src/common/helpers/is-appointment-date.helper.ts
  src/modules/appointment/appointment.service.ts
Labels: enhancement

#83 Fix/shown appointments fix
  src/common/constants/date.constants.ts
  src/modules/appointment/appointment.service.ts
Labels: bug

#85 fix: fix redirect link
  .env.example
  src/modules/appointment/appointment.service.ts
  src/modules/virtual-assessment/virtual-assessment.service.ts
Labels: bug
